
export interface Food {
  id: string;
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  serving: string;
  category: string;
}

export const foodDatabase: Food[] = [
  // Fruits
  { id: '1', name: 'Apple', calories: 95, protein: 0.5, carbs: 25, fat: 0.3, serving: '1 medium (182g)', category: 'Fruits' },
  { id: '2', name: 'Banana', calories: 105, protein: 1.3, carbs: 27, fat: 0.4, serving: '1 medium (118g)', category: 'Fruits' },
  { id: '3', name: 'Orange', calories: 62, protein: 1.2, carbs: 15.4, fat: 0.2, serving: '1 medium (154g)', category: 'Fruits' },
  { id: '4', name: 'Strawberries', calories: 49, protein: 1, carbs: 12, fat: 0.5, serving: '1 cup (152g)', category: 'Fruits' },
  { id: '5', name: 'Grapes', calories: 62, protein: 0.6, carbs: 16, fat: 0.3, serving: '1 cup (151g)', category: 'Fruits' },
  { id: '6', name: 'Blueberries', calories: 84, protein: 1.1, carbs: 21, fat: 0.5, serving: '1 cup (148g)', category: 'Fruits' },
  { id: '7', name: 'Watermelon', calories: 46, protein: 0.9, carbs: 12, fat: 0.2, serving: '1 cup (152g)', category: 'Fruits' },
  { id: '8', name: 'Pineapple', calories: 82, protein: 0.9, carbs: 22, fat: 0.2, serving: '1 cup (165g)', category: 'Fruits' },
  { id: '51', name: 'Mango', calories: 107, protein: 0.8, carbs: 28, fat: 0.4, serving: '1 cup (165g)', category: 'Fruits' },
  { id: '52', name: 'Peach', calories: 59, protein: 1.4, carbs: 14, fat: 0.4, serving: '1 medium (154g)', category: 'Fruits' },
  { id: '53', name: 'Pear', calories: 102, protein: 0.6, carbs: 27, fat: 0.2, serving: '1 medium (178g)', category: 'Fruits' },
  { id: '54', name: 'Kiwi', calories: 61, protein: 1.1, carbs: 15, fat: 0.5, serving: '1 medium (76g)', category: 'Fruits' },
  { id: '55', name: 'Cantaloupe', calories: 54, protein: 1.3, carbs: 13, fat: 0.3, serving: '1 cup (160g)', category: 'Fruits' },
  { id: '56', name: 'Raspberries', calories: 64, protein: 1.5, carbs: 15, fat: 0.8, serving: '1 cup (123g)', category: 'Fruits' },
  { id: '57', name: 'Blackberries', calories: 62, protein: 2, carbs: 14, fat: 0.7, serving: '1 cup (144g)', category: 'Fruits' },
  { id: '58', name: 'Cherries', calories: 87, protein: 1.5, carbs: 22, fat: 0.3, serving: '1 cup (154g)', category: 'Fruits' },
  { id: '59', name: 'Papaya', calories: 55, protein: 0.9, carbs: 14, fat: 0.2, serving: '1 cup (145g)', category: 'Fruits' },
  { id: '60', name: 'Avocado', calories: 234, protein: 2.9, carbs: 12, fat: 21, serving: '1 medium (150g)', category: 'Fruits' },
  { id: '61', name: 'Lemon', calories: 17, protein: 0.6, carbs: 5.4, fat: 0.2, serving: '1 medium (60g)', category: 'Fruits' },
  { id: '62', name: 'Lime', calories: 20, protein: 0.5, carbs: 7, fat: 0.1, serving: '1 medium (67g)', category: 'Fruits' },

  // Vegetables
  { id: '9', name: 'Broccoli', calories: 55, protein: 3.7, carbs: 11, fat: 0.6, serving: '1 cup (156g)', category: 'Vegetables' },
  { id: '10', name: 'Spinach', calories: 7, protein: 0.9, carbs: 1.1, fat: 0.1, serving: '1 cup (30g)', category: 'Vegetables' },
  { id: '11', name: 'Carrots', calories: 52, protein: 1.2, carbs: 12, fat: 0.3, serving: '1 cup (128g)', category: 'Vegetables' },
  { id: '12', name: 'Bell Pepper', calories: 30, protein: 1, carbs: 7, fat: 0.3, serving: '1 medium (119g)', category: 'Vegetables' },
  { id: '13', name: 'Tomato', calories: 32, protein: 1.6, carbs: 7, fat: 0.4, serving: '1 medium (182g)', category: 'Vegetables' },
  { id: '14', name: 'Cucumber', calories: 16, protein: 0.7, carbs: 4, fat: 0.1, serving: '1 cup (119g)', category: 'Vegetables' },
  { id: '15', name: 'Lettuce', calories: 10, protein: 0.9, carbs: 2, fat: 0.2, serving: '1 cup (72g)', category: 'Vegetables' },
  { id: '16', name: 'Sweet Potato', calories: 103, protein: 2.3, carbs: 24, fat: 0.1, serving: '1 medium (128g)', category: 'Vegetables' },
  { id: '63', name: 'Cauliflower', calories: 25, protein: 2, carbs: 5, fat: 0.3, serving: '1 cup (100g)', category: 'Vegetables' },
  { id: '64', name: 'Brussels Sprouts', calories: 38, protein: 3, carbs: 8, fat: 0.3, serving: '1 cup (88g)', category: 'Vegetables' },
  { id: '65', name: 'Asparagus', calories: 20, protein: 2.2, carbs: 4, fat: 0.1, serving: '1 cup (134g)', category: 'Vegetables' },
  { id: '66', name: 'Green Beans', calories: 35, protein: 2, carbs: 8, fat: 0.3, serving: '1 cup (125g)', category: 'Vegetables' },
  { id: '67', name: 'Zucchini', calories: 20, protein: 1.5, carbs: 4, fat: 0.4, serving: '1 cup (124g)', category: 'Vegetables' },
  { id: '68', name: 'Eggplant', calories: 20, protein: 0.8, carbs: 5, fat: 0.2, serving: '1 cup (82g)', category: 'Vegetables' },
  { id: '69', name: 'Kale', calories: 33, protein: 2.9, carbs: 7, fat: 0.6, serving: '1 cup (67g)', category: 'Vegetables' },
  { id: '70', name: 'Cabbage', calories: 22, protein: 1.1, carbs: 5, fat: 0.1, serving: '1 cup (89g)', category: 'Vegetables' },
  { id: '71', name: 'Celery', calories: 14, protein: 0.7, carbs: 3, fat: 0.2, serving: '1 cup (101g)', category: 'Vegetables' },
  { id: '72', name: 'Onion', calories: 64, protein: 1.8, carbs: 15, fat: 0.2, serving: '1 medium (110g)', category: 'Vegetables' },
  { id: '73', name: 'Garlic', calories: 4, protein: 0.2, carbs: 1, fat: 0, serving: '1 clove (3g)', category: 'Vegetables' },
  { id: '74', name: 'Mushrooms', calories: 15, protein: 2.2, carbs: 2.3, fat: 0.2, serving: '1 cup (70g)', category: 'Vegetables' },

  // Proteins
  { id: '17', name: 'Chicken Breast', calories: 231, protein: 43.5, carbs: 0, fat: 5, serving: '100g', category: 'Proteins' },
  { id: '18', name: 'Salmon', calories: 208, protein: 22, carbs: 0, fat: 12, serving: '100g', category: 'Proteins' },
  { id: '19', name: 'Ground Beef (90% lean)', calories: 176, protein: 20, carbs: 0, fat: 10, serving: '100g', category: 'Proteins' },
  { id: '20', name: 'Eggs', calories: 155, protein: 13, carbs: 1.1, fat: 11, serving: '2 large eggs', category: 'Proteins' },
  { id: '21', name: 'Tuna (canned in water)', calories: 116, protein: 25.5, carbs: 0, fat: 0.8, serving: '100g', category: 'Proteins' },
  { id: '22', name: 'Greek Yogurt (plain)', calories: 100, protein: 17, carbs: 6, fat: 0.4, serving: '170g container', category: 'Proteins' },
  { id: '23', name: 'Tofu', calories: 94, protein: 10, carbs: 2.3, fat: 6, serving: '100g', category: 'Proteins' },
  { id: '24', name: 'Black Beans', calories: 227, protein: 15, carbs: 41, fat: 0.9, serving: '1 cup (172g)', category: 'Proteins' },
  { id: '75', name: 'Turkey Breast', calories: 189, protein: 29, carbs: 0, fat: 7, serving: '100g', category: 'Proteins' },
  { id: '76', name: 'Cod', calories: 105, protein: 23, carbs: 0, fat: 0.9, serving: '100g', category: 'Proteins' },
  { id: '77', name: 'Shrimp', calories: 99, protein: 18, carbs: 0.2, fat: 1.4, serving: '100g', category: 'Proteins' },
  { id: '78', name: 'Pork Tenderloin', calories: 143, protein: 26, carbs: 0, fat: 3.5, serving: '100g', category: 'Proteins' },
  { id: '79', name: 'Lamb', calories: 294, protein: 25, carbs: 0, fat: 21, serving: '100g', category: 'Proteins' },
  { id: '80', name: 'Duck', calories: 337, protein: 19, carbs: 0, fat: 28, serving: '100g', category: 'Proteins' },
  { id: '81', name: 'Chickpeas', calories: 269, protein: 15, carbs: 45, fat: 4.3, serving: '1 cup (164g)', category: 'Proteins' },
  { id: '82', name: 'Lentils', calories: 230, protein: 18, carbs: 40, fat: 0.8, serving: '1 cup (198g)', category: 'Proteins' },
  { id: '83', name: 'Kidney Beans', calories: 225, protein: 15, carbs: 40, fat: 0.9, serving: '1 cup (177g)', category: 'Proteins' },
  { id: '84', name: 'Tempeh', calories: 193, protein: 20, carbs: 9, fat: 11, serving: '100g', category: 'Proteins' },
  { id: '85', name: 'Seitan', calories: 370, protein: 75, carbs: 14, fat: 1.9, serving: '100g', category: 'Proteins' },
  { id: '86', name: 'Protein Powder', calories: 103, protein: 20, carbs: 3, fat: 1.5, serving: '1 scoop (30g)', category: 'Proteins' },

  // Grains & Carbs
  { id: '25', name: 'White Rice (cooked)', calories: 205, protein: 4.3, carbs: 45, fat: 0.4, serving: '1 cup (158g)', category: 'Grains' },
  { id: '26', name: 'Brown Rice (cooked)', calories: 216, protein: 5, carbs: 45, fat: 1.8, serving: '1 cup (195g)', category: 'Grains' },
  { id: '27', name: 'Quinoa (cooked)', calories: 222, protein: 8, carbs: 39, fat: 3.6, serving: '1 cup (185g)', category: 'Grains' },
  { id: '28', name: 'Oatmeal (cooked)', calories: 154, protein: 6, carbs: 28, fat: 3, serving: '1 cup (234g)', category: 'Grains' },
  { id: '29', name: 'Whole Wheat Bread', calories: 81, protein: 4, carbs: 14, fat: 1.1, serving: '1 slice (28g)', category: 'Grains' },
  { id: '30', name: 'Pasta (cooked)', calories: 220, protein: 8, carbs: 44, fat: 1.1, serving: '1 cup (140g)', category: 'Grains' },
  { id: '31', name: 'Sweet Potato', calories: 103, protein: 2.3, carbs: 24, fat: 0.1, serving: '1 medium (128g)', category: 'Grains' },
  { id: '87', name: 'Barley (cooked)', calories: 193, protein: 3.6, carbs: 44, fat: 0.7, serving: '1 cup (157g)', category: 'Grains' },
  { id: '88', name: 'Bulgur (cooked)', calories: 151, protein: 5.6, carbs: 34, fat: 0.4, serving: '1 cup (182g)', category: 'Grains' },
  { id: '89', name: 'Millet (cooked)', calories: 207, protein: 6.1, carbs: 41, fat: 1.7, serving: '1 cup (174g)', category: 'Grains' },
  { id: '90', name: 'Buckwheat (cooked)', calories: 155, protein: 5.7, carbs: 33, fat: 1, serving: '1 cup (168g)', category: 'Grains' },
  { id: '91', name: 'Couscous (cooked)', calories: 176, protein: 6, carbs: 36, fat: 0.3, serving: '1 cup (157g)', category: 'Grains' },
  { id: '92', name: 'Wild Rice (cooked)', calories: 166, protein: 6.5, carbs: 35, fat: 0.6, serving: '1 cup (164g)', category: 'Grains' },
  { id: '93', name: 'Rye Bread', calories: 83, protein: 2.7, carbs: 15, fat: 1.1, serving: '1 slice (32g)', category: 'Grains' },
  { id: '94', name: 'Sourdough Bread', calories: 93, protein: 3.8, carbs: 18, fat: 0.6, serving: '1 slice (36g)', category: 'Grains' },
  { id: '95', name: 'Bagel', calories: 245, protein: 10, carbs: 48, fat: 1.4, serving: '1 medium (89g)', category: 'Grains' },
  { id: '96', name: 'English Muffin', calories: 134, protein: 4.4, carbs: 26, fat: 1, serving: '1 muffin (57g)', category: 'Grains' },
  { id: '97', name: 'Tortilla (flour)', calories: 159, protein: 4.4, carbs: 27, fat: 3.6, serving: '1 large (49g)', category: 'Grains' },
  { id: '98', name: 'Pita Bread', calories: 165, protein: 5.5, carbs: 33, fat: 0.7, serving: '1 pita (60g)', category: 'Grains' },
  { id: '99', name: 'Crackers', calories: 142, protein: 2.4, carbs: 18, fat: 7, serving: '1 oz (28g)', category: 'Grains' },

  // Dairy
  { id: '32', name: 'Milk (2%)', calories: 122, protein: 8, carbs: 12, fat: 4.8, serving: '1 cup (244g)', category: 'Dairy' },
  { id: '33', name: 'Cheddar Cheese', calories: 113, protein: 7, carbs: 1, fat: 9, serving: '1 oz (28g)', category: 'Dairy' },
  { id: '34', name: 'Cottage Cheese', calories: 206, protein: 23, carbs: 8, fat: 9, serving: '1 cup (226g)', category: 'Dairy' },
  { id: '35', name: 'Yogurt (plain)', calories: 154, protein: 13, carbs: 17, fat: 4, serving: '1 cup (245g)', category: 'Dairy' },
  { id: '100', name: 'Whole Milk', calories: 149, protein: 8, carbs: 12, fat: 8, serving: '1 cup (244g)', category: 'Dairy' },
  { id: '101', name: 'Skim Milk', calories: 83, protein: 8.3, carbs: 12, fat: 0.2, serving: '1 cup (245g)', category: 'Dairy' },
  { id: '102', name: 'Almond Milk', calories: 39, protein: 1.5, carbs: 3.4, fat: 2.9, serving: '1 cup (240ml)', category: 'Dairy' },
  { id: '103', name: 'Soy Milk', calories: 80, protein: 7, carbs: 4, fat: 4, serving: '1 cup (240ml)', category: 'Dairy' },
  { id: '104', name: 'Oat Milk', calories: 120, protein: 3, carbs: 16, fat: 5, serving: '1 cup (240ml)', category: 'Dairy' },
  { id: '105', name: 'Mozzarella Cheese', calories: 85, protein: 6.3, carbs: 0.6, fat: 6.3, serving: '1 oz (28g)', category: 'Dairy' },
  { id: '106', name: 'Swiss Cheese', calories: 108, protein: 7.6, carbs: 1.5, fat: 7.9, serving: '1 oz (28g)', category: 'Dairy' },
  { id: '107', name: 'Parmesan Cheese', calories: 108, protein: 9.6, carbs: 1, fat: 7.3, serving: '1 oz (28g)', category: 'Dairy' },
  { id: '108', name: 'Cream Cheese', calories: 99, protein: 1.8, carbs: 1.6, fat: 9.9, serving: '1 oz (28g)', category: 'Dairy' },
  { id: '109', name: 'Butter', calories: 102, protein: 0.1, carbs: 0, fat: 11.5, serving: '1 tbsp (14g)', category: 'Dairy' },
  { id: '110', name: 'Heavy Cream', calories: 52, protein: 0.4, carbs: 0.4, fat: 5.5, serving: '1 tbsp (15ml)', category: 'Dairy' },

  // Nuts & Seeds
  { id: '36', name: 'Almonds', calories: 164, protein: 6, carbs: 6, fat: 14, serving: '1 oz (28g)', category: 'Nuts & Seeds' },
  { id: '37', name: 'Peanut Butter', calories: 188, protein: 8, carbs: 8, fat: 16, serving: '2 tbsp (32g)', category: 'Nuts & Seeds' },
  { id: '38', name: 'Walnuts', calories: 185, protein: 4.3, carbs: 3.9, fat: 18.5, serving: '1 oz (28g)', category: 'Nuts & Seeds' },
  { id: '39', name: 'Sunflower Seeds', calories: 165, protein: 5.8, carbs: 6.8, fat: 14, serving: '1 oz (28g)', category: 'Nuts & Seeds' },
  { id: '111', name: 'Cashews', calories: 157, protein: 5.2, carbs: 8.6, fat: 12.4, serving: '1 oz (28g)', category: 'Nuts & Seeds' },
  { id: '112', name: 'Pistachios', calories: 159, protein: 5.7, carbs: 7.9, fat: 12.9, serving: '1 oz (28g)', category: 'Nuts & Seeds' },
  { id: '113', name: 'Brazil Nuts', calories: 186, protein: 4.1, carbs: 3.3, fat: 19, serving: '1 oz (28g)', category: 'Nuts & Seeds' },
  { id: '114', name: 'Pecans', calories: 196, protein: 2.6, carbs: 3.9, fat: 20.4, serving: '1 oz (28g)', category: 'Nuts & Seeds' },
  { id: '115', name: 'Macadamia Nuts', calories: 204, protein: 2.2, carbs: 3.9, fat: 21.5, serving: '1 oz (28g)', category: 'Nuts & Seeds' },
  { id: '116', name: 'Hazelnuts', calories: 178, protein: 4.2, carbs: 4.7, fat: 17.2, serving: '1 oz (28g)', category: 'Nuts & Seeds' },
  { id: '117', name: 'Pumpkin Seeds', calories: 151, protein: 7, carbs: 5, fat: 13, serving: '1 oz (28g)', category: 'Nuts & Seeds' },
  { id: '118', name: 'Chia Seeds', calories: 137, protein: 4.4, carbs: 12, fat: 8.6, serving: '1 oz (28g)', category: 'Nuts & Seeds' },
  { id: '119', name: 'Flax Seeds', calories: 151, protein: 5.2, carbs: 8.1, fat: 11.9, serving: '1 oz (28g)', category: 'Nuts & Seeds' },
  { id: '120', name: 'Sesame Seeds', calories: 160, protein: 5, carbs: 7.3, fat: 13.9, serving: '1 oz (28g)', category: 'Nuts & Seeds' },

  // Fast Food & Snacks
  { id: '40', name: 'French Fries (medium)', calories: 365, protein: 4, carbs: 48, fat: 17, serving: '1 serving (115g)', category: 'Fast Food' },
  { id: '41', name: 'Pizza Slice (pepperoni)', calories: 298, protein: 13, carbs: 36, fat: 11, serving: '1 slice (107g)', category: 'Fast Food' },
  { id: '42', name: 'Hamburger', calories: 540, protein: 25, carbs: 40, fat: 31, serving: '1 burger (150g)', category: 'Fast Food' },
  { id: '43', name: 'Potato Chips', calories: 152, protein: 2, carbs: 15, fat: 10, serving: '1 oz (28g)', category: 'Snacks' },
  { id: '44', name: 'Chocolate Chip Cookie', calories: 78, protein: 1, carbs: 11, fat: 3.7, serving: '1 cookie (16g)', category: 'Snacks' },
  { id: '45', name: 'Ice Cream (vanilla)', calories: 137, protein: 2.3, carbs: 16, fat: 7, serving: '1/2 cup (66g)', category: 'Snacks' },
  { id: '121', name: 'Cheeseburger', calories: 535, protein: 26, carbs: 40, fat: 31, serving: '1 burger (154g)', category: 'Fast Food' },
  { id: '122', name: 'Chicken Nuggets', calories: 319, protein: 13, carbs: 16, fat: 24, serving: '6 pieces (102g)', category: 'Fast Food' },
  { id: '123', name: 'Hot Dog', calories: 290, protein: 10, carbs: 25, fat: 17, serving: '1 hot dog (98g)', category: 'Fast Food' },
  { id: '124', name: 'Taco', calories: 226, protein: 10, carbs: 18, fat: 13, serving: '1 taco (102g)', category: 'Fast Food' },
  { id: '125', name: 'Burrito', calories: 448, protein: 14, carbs: 71, fat: 14, serving: '1 burrito (219g)', category: 'Fast Food' },
  { id: '126', name: 'Sandwich (turkey)', calories: 329, protein: 22, carbs: 26, fat: 15, serving: '1 sandwich (146g)', category: 'Fast Food' },
  { id: '127', name: 'Onion Rings', calories: 411, protein: 5.6, carbs: 38, fat: 26, serving: '10 rings (83g)', category: 'Fast Food' },
  { id: '128', name: 'Pretzels', calories: 108, protein: 2.8, carbs: 22, fat: 0.8, serving: '1 oz (28g)', category: 'Snacks' },
  { id: '129', name: 'Popcorn', calories: 31, protein: 1, carbs: 6.2, fat: 0.4, serving: '1 cup (8g)', category: 'Snacks' },
  { id: '130', name: 'Granola Bar', calories: 118, protein: 2.5, carbs: 16, fat: 4.9, serving: '1 bar (28g)', category: 'Snacks' },
  { id: '131', name: 'Dark Chocolate', calories: 170, protein: 2.2, carbs: 13, fat: 12, serving: '1 oz (28g)', category: 'Snacks' },
  { id: '132', name: 'Milk Chocolate', calories: 150, protein: 2, carbs: 17, fat: 8.5, serving: '1 oz (28g)', category: 'Snacks' },
  { id: '133', name: 'Donut (glazed)', calories: 269, protein: 4, carbs: 31, fat: 15, serving: '1 donut (60g)', category: 'Snacks' },
  { id: '134', name: 'Muffin (blueberry)', calories: 313, protein: 6, carbs: 54, fat: 7, serving: '1 muffin (113g)', category: 'Snacks' },

  // Beverages
  { id: '46', name: 'Coffee (black)', calories: 2, protein: 0.3, carbs: 0, fat: 0, serving: '1 cup (240ml)', category: 'Beverages' },
  { id: '47', name: 'Green Tea', calories: 2, protein: 0, carbs: 0, fat: 0, serving: '1 cup (240ml)', category: 'Beverages' },
  { id: '48', name: 'Orange Juice', calories: 112, protein: 1.7, carbs: 26, fat: 0.5, serving: '1 cup (248ml)', category: 'Beverages' },
  { id: '49', name: 'Coca Cola', calories: 140, protein: 0, carbs: 39, fat: 0, serving: '12 oz can (355ml)', category: 'Beverages' },
  { id: '50', name: 'Beer', calories: 153, protein: 1.6, carbs: 13, fat: 0, serving: '12 oz (355ml)', category: 'Beverages' },
  { id: '135', name: 'Apple Juice', calories: 114, protein: 0.2, carbs: 28, fat: 0.3, serving: '1 cup (248ml)', category: 'Beverages' },
  { id: '136', name: 'Grape Juice', calories: 152, protein: 1.4, carbs: 37, fat: 0.2, serving: '1 cup (253ml)', category: 'Beverages' },
  { id: '137', name: 'Lemonade', calories: 99, protein: 0.1, carbs: 26, fat: 0.1, serving: '1 cup (248ml)', category: 'Beverages' },
  { id: '138', name: 'Sports Drink', calories: 50, protein: 0, carbs: 14, fat: 0, serving: '8 oz (240ml)', category: 'Beverages' },
  { id: '139', name: 'Energy Drink', calories: 110, protein: 0, carbs: 28, fat: 0, serving: '8.4 oz (248ml)', category: 'Beverages' },
  { id: '140', name: 'Wine (red)', calories: 125, protein: 0.1, carbs: 3.8, fat: 0, serving: '5 oz (147ml)', category: 'Beverages' },
  { id: '141', name: 'Wine (white)', calories: 121, protein: 0.1, carbs: 3.8, fat: 0, serving: '5 oz (147ml)', category: 'Beverages' },
  { id: '142', name: 'Smoothie (fruit)', calories: 145, protein: 2.1, carbs: 34, fat: 0.5, serving: '1 cup (240ml)', category: 'Beverages' },
  { id: '143', name: 'Protein Shake', calories: 140, protein: 25, carbs: 5, fat: 2, serving: '1 cup (240ml)', category: 'Beverages' },
  { id: '144', name: 'Iced Tea', calories: 70, protein: 0, carbs: 18, fat: 0, serving: '12 oz (355ml)', category: 'Beverages' },
  { id: '145', name: 'Hot Chocolate', calories: 192, protein: 8.8, carbs: 27, fat: 5.8, serving: '1 cup (240ml)', category: 'Beverages' },
  { id: '146', name: 'Coconut Water', calories: 46, protein: 1.7, carbs: 8.9, fat: 0.5, serving: '1 cup (240ml)', category: 'Beverages' },
  { id: '147', name: 'Kombucha', calories: 30, protein: 0, carbs: 7, fat: 0, serving: '8 oz (240ml)', category: 'Beverages' },
  { id: '148', name: 'Matcha Latte', calories: 70, protein: 1, carbs: 8, fat: 3.5, serving: '8 oz (240ml)', category: 'Beverages' },
  { id: '149', name: 'Cappuccino', calories: 80, protein: 4, carbs: 6, fat: 4, serving: '8 oz (240ml)', category: 'Beverages' },
  { id: '150', name: 'Espresso', calories: 9, protein: 0.5, carbs: 1.6, fat: 0.2, serving: '1 shot (30ml)', category: 'Beverages' },

  // Indian Foods
  { id: '151', name: 'Basmati Rice (cooked)', calories: 210, protein: 4.4, carbs: 45, fat: 0.5, serving: '1 cup (158g)', category: 'Indian Food' },
  { id: '152', name: 'Chicken Curry', calories: 280, protein: 22, carbs: 8, fat: 18, serving: '1 cup (240ml)', category: 'Indian Food' },
  { id: '153', name: 'Dal (lentil curry)', calories: 180, protein: 12, carbs: 30, fat: 2, serving: '1 cup (240ml)', category: 'Indian Food' },
  { id: '154', name: 'Naan Bread', calories: 262, protein: 9, carbs: 45, fat: 5, serving: '1 piece (90g)', category: 'Indian Food' },
  { id: '155', name: 'Chapati/Roti', calories: 104, protein: 3, carbs: 18, fat: 2.5, serving: '1 piece (40g)', category: 'Indian Food' },
  { id: '156', name: 'Samosa', calories: 308, protein: 5, carbs: 32, fat: 19, serving: '1 piece (100g)', category: 'Indian Food' },
  { id: '157', name: 'Biryani (chicken)', calories: 420, protein: 18, carbs: 58, fat: 12, serving: '1 cup (200g)', category: 'Indian Food' },
  { id: '158', name: 'Tandoori Chicken', calories: 190, protein: 35, carbs: 2, fat: 4, serving: '100g', category: 'Indian Food' },
  { id: '159', name: 'Paneer Curry', calories: 320, protein: 14, carbs: 12, fat: 25, serving: '1 cup (240ml)', category: 'Indian Food' },
  { id: '160', name: 'Saag (spinach curry)', calories: 150, protein: 8, carbs: 12, fat: 8, serving: '1 cup (240ml)', category: 'Indian Food' },
  { id: '161', name: 'Rajma (kidney bean curry)', calories: 200, protein: 12, carbs: 35, fat: 2, serving: '1 cup (240ml)', category: 'Indian Food' },
  { id: '162', name: 'Aloo Gobi', calories: 180, protein: 4, carbs: 28, fat: 6, serving: '1 cup (200g)', category: 'Indian Food' },
  { id: '163', name: 'Butter Chicken', calories: 350, protein: 20, carbs: 10, fat: 25, serving: '1 cup (240ml)', category: 'Indian Food' },
  { id: '164', name: 'Masala Dosa', calories: 168, protein: 4, carbs: 25, fat: 6, serving: '1 piece (100g)', category: 'Indian Food' },
  { id: '165', name: 'Idli', calories: 58, protein: 2, carbs: 12, fat: 0.3, serving: '1 piece (30g)', category: 'Indian Food' },
  { id: '166', name: 'Vada', calories: 157, protein: 6, carbs: 15, fat: 8, serving: '1 piece (50g)', category: 'Indian Food' },
  { id: '167', name: 'Upma', calories: 135, protein: 3, carbs: 23, fat: 3, serving: '1 cup (150g)', category: 'Indian Food' },
  { id: '168', name: 'Poha', calories: 180, protein: 4, carbs: 35, fat: 3, serving: '1 cup (150g)', category: 'Indian Food' },
  { id: '169', name: 'Pakora', calories: 320, protein: 8, carbs: 25, fat: 22, serving: '100g', category: 'Indian Food' },
  { id: '170', name: 'Chole (chickpea curry)', calories: 210, protein: 10, carbs: 32, fat: 5, serving: '1 cup (240ml)', category: 'Indian Food' },
  { id: '171', name: 'Palak Paneer', calories: 280, protein: 12, carbs: 8, fat: 22, serving: '1 cup (240ml)', category: 'Indian Food' },
  { id: '172', name: 'Matar Paneer', calories: 250, protein: 11, carbs: 15, fat: 18, serving: '1 cup (240ml)', category: 'Indian Food' },
  { id: '173', name: 'Kheer (rice pudding)', calories: 387, protein: 8, carbs: 65, fat: 10, serving: '1 cup (240ml)', category: 'Indian Food' },
  { id: '174', name: 'Gulab Jamun', calories: 143, protein: 3, carbs: 20, fat: 6, serving: '1 piece (25g)', category: 'Indian Food' },
  { id: '175', name: 'Lassi (mango)', calories: 180, protein: 6, carbs: 30, fat: 4, serving: '1 cup (240ml)', category: 'Indian Food' },
  { id: '176', name: 'Masala Chai', calories: 70, protein: 2, carbs: 12, fat: 2, serving: '1 cup (240ml)', category: 'Indian Food' },
  { id: '177', name: 'Bhel Puri', calories: 220, protein: 5, carbs: 38, fat: 6, serving: '1 cup (100g)', category: 'Indian Food' },
  { id: '178', name: 'Pani Puri', calories: 25, protein: 1, carbs: 4, fat: 1, serving: '1 piece (10g)', category: 'Indian Food' },
  { id: '179', name: 'Dhokla', calories: 160, protein: 4, carbs: 24, fat: 5, serving: '1 piece (100g)', category: 'Indian Food' },
  { id: '180', name: 'Kachori', calories: 280, protein: 6, carbs: 30, fat: 15, serving: '1 piece (70g)', category: 'Indian Food' },

  // Trader Joe's Products
  { id: '181', name: 'TJ\'s Cauliflower Gnocchi', calories: 140, protein: 3, carbs: 22, fat: 3, serving: '1 cup (140g)', category: 'Trader Joe\'s' },
  { id: '182', name: 'TJ\'s Everything Bagel Seasoning', calories: 0, protein: 0, carbs: 0, fat: 0, serving: '1/4 tsp (1g)', category: 'Trader Joe\'s' },
  { id: '183', name: 'TJ\'s Mandarin Orange Chicken', calories: 320, protein: 15, carbs: 36, fat: 13, serving: '1 cup (140g)', category: 'Trader Joe\'s' },
  { id: '184', name: 'TJ\'s Cookie Butter', calories: 90, protein: 1, carbs: 11, fat: 5.5, serving: '1 tbsp (15g)', category: 'Trader Joe\'s' },
  { id: '185', name: 'TJ\'s Two Buck Chuck Wine', calories: 125, protein: 0.1, carbs: 4, fat: 0, serving: '5 oz (147ml)', category: 'Trader Joe\'s' },
  { id: '186', name: 'TJ\'s Unexpected Cheddar', calories: 110, protein: 7, carbs: 0, fat: 9, serving: '1 oz (28g)', category: 'Trader Joe\'s' },
  { id: '187', name: 'TJ\'s Hatch Chile Mac & Cheese', calories: 270, protein: 11, carbs: 39, fat: 8, serving: '1 cup (140g)', category: 'Trader Joe\'s' },
  { id: '188', name: 'TJ\'s Peanut Butter Filled Pretzels', calories: 140, protein: 5, carbs: 16, fat: 6, serving: '1 oz (28g)', category: 'Trader Joe\'s' },
  { id: '189', name: 'TJ\'s Dark Chocolate Peanut Butter Cups', calories: 180, protein: 4, carbs: 17, fat: 12, serving: '2 cups (35g)', category: 'Trader Joe\'s' },
  { id: '190', name: 'TJ\'s Frozen Mango Chunks', calories: 60, protein: 1, carbs: 15, fat: 0, serving: '2/3 cup (100g)', category: 'Trader Joe\'s' },
  { id: '191', name: 'TJ\'s Organic Coconut Strips', calories: 120, protein: 2, carbs: 8, fat: 9, serving: '1 oz (28g)', category: 'Trader Joe\'s' },
  { id: '192', name: 'TJ\'s Almond Butter', calories: 190, protein: 7, carbs: 7, fat: 17, serving: '2 tbsp (32g)', category: 'Trader Joe\'s' },
  { id: '193', name: 'TJ\'s Triple Ginger Snaps', calories: 140, protein: 2, carbs: 22, fat: 5, serving: '4 cookies (32g)', category: 'Trader Joe\'s' },
  { id: '194', name: 'TJ\'s Organic Marinara Sauce', calories: 35, protein: 1, carbs: 7, fat: 0, serving: '1/2 cup (125g)', category: 'Trader Joe\'s' },
  { id: '195', name: 'TJ\'s Chicken Tikka Masala', calories: 270, protein: 16, carbs: 38, fat: 7, serving: '1 package (280g)', category: 'Trader Joe\'s' },
  { id: '196', name: 'TJ\'s Frozen Acai Bowl', calories: 290, protein: 4, carbs: 58, fat: 6, serving: '1 bowl (156g)', category: 'Trader Joe\'s' },
  { id: '197', name: 'TJ\'s Green Goddess Salad Dressing', calories: 130, protein: 1, carbs: 2, fat: 14, serving: '2 tbsp (30ml)', category: 'Trader Joe\'s' },
  { id: '198', name: 'TJ\'s Organic Pasta Sauce', calories: 60, protein: 2, carbs: 11, fat: 1.5, serving: '1/2 cup (125g)', category: 'Trader Joe\'s' },
  { id: '199', name: 'TJ\'s Mediterranean Hummus', calories: 50, protein: 2, carbs: 4, fat: 3, serving: '2 tbsp (28g)', category: 'Trader Joe\'s' },
  { id: '200', name: 'TJ\'s Organic Brown Rice', calories: 216, protein: 5, carbs: 45, fat: 1.8, serving: '1 cup (195g)', category: 'Trader Joe\'s' },
  { id: '201', name: 'TJ\'s Chocolate Croissants', calories: 300, protein: 5, carbs: 27, fat: 19, serving: '1 croissant (65g)', category: 'Trader Joe\'s' },
  { id: '202', name: 'TJ\'s Organic Arugula', calories: 5, protein: 0.5, carbs: 1, fat: 0.1, serving: '1 cup (20g)', category: 'Trader Joe\'s' },
  { id: '203', name: 'TJ\'s Frozen Vegetable Fried Rice', calories: 250, protein: 8, carbs: 43, fat: 6, serving: '1 cup (140g)', category: 'Trader Joe\'s' },
  { id: '204', name: 'TJ\'s Organic Quinoa', calories: 170, protein: 6, carbs: 30, fat: 3, serving: '1/4 cup dry (43g)', category: 'Trader Joe\'s' },
  { id: '205', name: 'TJ\'s Pesto Genovese', calories: 240, protein: 4, carbs: 3, fat: 24, serving: '1/4 cup (65g)', category: 'Trader Joe\'s' },
  { id: '206', name: 'TJ\'s Frozen Berry Medley', calories: 70, protein: 1, carbs: 16, fat: 0.5, serving: '1 cup (140g)', category: 'Trader Joe\'s' },
  { id: '207', name: 'TJ\'s Organic Whole Milk Yogurt', calories: 150, protein: 8, carbs: 16, fat: 6, serving: '1 container (170g)', category: 'Trader Joe\'s' },
  { id: '208', name: 'TJ\'s Spicy Peanut Vindaloo', calories: 350, protein: 12, carbs: 48, fat: 12, serving: '1 package (340g)', category: 'Trader Joe\'s' },
  { id: '209', name: 'TJ\'s Organic Coconut Water', calories: 45, protein: 0, carbs: 11, fat: 0, serving: '1 bottle (500ml)', category: 'Trader Joe\'s' },
  { id: '210', name: 'TJ\'s Frozen Strawberries', calories: 50, protein: 1, carbs: 13, fat: 0, serving: '1 cup (140g)', category: 'Trader Joe\'s' },
  { id: '211', name: 'TJ\'s Almond Croissants', calories: 320, protein: 7, carbs: 26, fat: 21, serving: '1 croissant (70g)', category: 'Trader Joe\'s' },
  { id: '212', name: 'TJ\'s Organic Baby Spinach', calories: 20, protein: 2, carbs: 3, fat: 0.3, serving: '3 cups (85g)', category: 'Trader Joe\'s' },
  { id: '213', name: 'TJ\'s Frozen Pad Thai', calories: 340, protein: 12, carbs: 54, fat: 10, serving: '1 package (340g)', category: 'Trader Joe\'s' },
  { id: '214', name: 'TJ\'s Organic Ketchup', calories: 20, protein: 0, carbs: 5, fat: 0, serving: '1 tbsp (17g)', category: 'Trader Joe\'s' },
  { id: '215', name: 'TJ\'s Dark Chocolate Almonds', calories: 150, protein: 4, carbs: 12, fat: 10, serving: '1/4 cup (30g)', category: 'Trader Joe\'s' },
  { id: '216', name: 'TJ\'s Organic Bananas', calories: 105, protein: 1.3, carbs: 27, fat: 0.4, serving: '1 medium (118g)', category: 'Trader Joe\'s' },
  { id: '217', name: 'TJ\'s Frozen Mac & Cheese', calories: 330, protein: 14, carbs: 41, fat: 12, serving: '1 cup (140g)', category: 'Trader Joe\'s' },
  { id: '218', name: 'TJ\'s Organic Olive Oil', calories: 120, protein: 0, carbs: 0, fat: 14, serving: '1 tbsp (14ml)', category: 'Trader Joe\'s' },
  { id: '219', name: 'TJ\'s Frozen Blueberries', calories: 80, protein: 1, carbs: 19, fat: 0.5, serving: '1 cup (140g)', category: 'Trader Joe\'s' },
  { id: '220', name: 'TJ\'s Organic Whole Wheat Bread', calories: 80, protein: 4, carbs: 15, fat: 1.5, serving: '1 slice (28g)', category: 'Trader Joe\'s' }
];

export const categories = [
  'All',
  'Fruits',
  'Vegetables', 
  'Proteins',
  'Grains',
  'Dairy',
  'Nuts & Seeds',
  'Fast Food',
  'Snacks',
  'Beverages',
  'Indian Food',
  'Trader Joe\'s'
];

export function searchFoods(query: string, category: string = 'All'): Food[] {
  let filteredFoods = foodDatabase;
  
  if (category !== 'All') {
    filteredFoods = filteredFoods.filter(food => food.category === category);
  }
  
  if (query.trim()) {
    filteredFoods = filteredFoods.filter(food => 
      food.name.toLowerCase().includes(query.toLowerCase())
    );
  }
  
  return filteredFoods;
}
